#! /bin/bash

sxhkd &
nitrogen --restore &
~/.scripts/polybarstart.sh &
dunst -conf ~/.config/dunst/dunstrc &
~/.fehbg &
picom &

bspc monitor -d ' TERM' ' WEB' ' MEDIA' ' CHAT' ' MISC'

bspc config border_width         2
bspc config window_gap           0

bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

bspc config normal_border_color         "#000000" 
bspc config focused_border_color        "#424242"
bspc config presel_feedback_color       "#f7cac9"

bspc config automatic_scheme     longest_side
bspc config initial_polarity     second_child
bspc config ignore_ewmh_focus    true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true


bspc rule -a firefox desktop='^2'
bspc rule -a discord desktop='^4'
bspc rule -a mpv desktop='^3' state=fullscreen

bspc rule -s mpv fullscreen
