#! /bin/bash

sxhkd &
compton &
nitrogen --restore &
~/.scripts/polybarstart.sh &
dunst -conf ~/.config/dunst/dunstrc &

bspc monitor -d ' TERM' ' WEB' ' MEDIA' ' GAMES' ' CHAT' ' MISC'

bspc config border_width         3
bspc config window_gap           20

bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

bspc config normal_border_color         "#000000" 
bspc config focused_border_color        "#424242"
bspc config presel_feedback_color       "#f7cac9"

bspc config automatic_scheme     longest_side
bspc config initial_polarity     second_child
bspc config ignore_ewmh_focus    true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Firefox desktop='^2'
bspc rule -a Steam desktop='^4'
